source "$HOME/.sdkman/bin/sdkman-init.sh"
source "$HOME/.my-zsh/functions.zsh"
source "$HOME/.my-zsh/android-dev-support.zsh"
source "$HOME/.my-zsh/alias.zsh"
source "$HOME/.my-zsh/localpaths.zsh"
source "$HOME/.my-zsh/local-env-support.zsh"